name: Scully Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cmgriffing/scully-gh-pages-action@v1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          build-args: -- --prod --stats-json
          scully-args: -- --scanRoutes --showGuessError 
